### ISSUE TITLE
version > 0.29.0 fails to load on Mac

### ISSUE THREAD

**Issue by gaelforget** [mdashkezari/pycmap#1]
Up to v0.0.29 I am able to import `Pycmap` just fine on my mac, but any version after that gives me this error:

```
>>> import pycmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/pycmap/__init__.py", line 5, in <module>
    from .cmap import API  # noqa
  File "/anaconda3/lib/python3.7/site-packages/pycmap/cmap.py", line 11, in <module>
    from .rest import _REST
  File "/anaconda3/lib/python3.7/site-packages/pycmap/rest.py", line 16, in <module>
    from pandas.compat import StringIO
ImportError: cannot import name 'StringIO' from 'pandas.compat' (/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py)
```

This is what I have installed and generates the error:

```
Python 3.7.4
pandas                    0.25.1
pandas-datareader         0.7.0
```

For now I revert to v0.0.29 which loads fine but this means that I am stuck because v0.0.29 returns another error (that got fixed in v0.30.0) when I try to use `api.get_metadata` or `exportDataFlag=True`.

**Comment by mdashkezari** [comment]
this is a panads latest version error (0.25.0, 0.25.1).

read this thread carefully.
https://github.com/pydata/pandas-datareader/issues/655

please roll back to pandas 0.24.2

**Comment by mdashkezari** [comment]
**As the readme.md points out, this repo has transferred to simons cmap organization:**
https://github.com/simonscmap/pycmap

**Comment by mdashkezari** [comment]
forcing pycmap pandas dependency <= 0.24.2, until the upstream is fixed.

good finding!
