### ISSUE TITLE
Lack of Travis CI setup?

### ISSUE THREAD

**Issue by gaelforget** [mdashkezari/pycmap#2]
I do not see a <https://travis-ci.org/> badge on this repo. Maybe it's just missing from README.md but if otherwise please consider setting up automated testing that triggers a build and regression testing (on linux, osx, and ideally windows) anytime changes are pushed to the master branch. 

Otherwise, issues tend to go undetected and users can get stuck (see issue #1 for an example).

**Comment by mdashkezari** [comment]
good idea, some times in near future.
see the response to the mentioned issue.

**As the readme.md points out, this repo has transferred to simons cmap organization:**
https://github.com/simonscmap/pycmap
